### PR TITLE
GithHub autentication, I have a problem on this test: 'Via OAuth2 Tok…

### PR DESCRIPTION
**Pull request by Maosorio92**
…ens by Header', it is failing

Hello!
I found a problem on this test: 'Via OAuth2 Tokens by Header'

First, I set the Access Token, then, I run the tests, but I usually have to make "npm run lint -- --fix" first to fix problems, after that, I run the tests and this one is failing. So I continued with the next test:'Via OAuth2 Tokens by parameter', and that one is passing as I show on the following image. What should I do?

image

### CODE REVIEW

**Review by danielgalvis98 — COMMENTED** [review]
I see on the CI that both tests are passing https://github.com/Maosorio92/workshop-api-testing-js/runs/7117902496?check_suite_focus=true

Have you already solved the issue?

**Comment by Maosorio92** [comment]
When I see it in that Cl, both are passing, but in my local, the first one is not, why does it happen?

**Comment by Maosorio92** [comment]
image

**Comment by holgiosalos** [comment]
@Maosorio92 probably it is failing locally because you have not defined in your PC, the environment variable ACCESS_TOKEN, [review step 5 of this section](https://github.com/holgiosalos/workshop-api-testing-js-doc#autenticaci%C3%B3n-en-github)

**Review by holgiosalos — APPROVED** [review]

**Pull request merged**
